### ISSUE TITLE
Warning emitted by superfluous call to WriteHeader

### ISSUE THREAD

**Issue by tazimmerman** [samber/slog-http#2]
Hi,

I ran into this warning yesterday when using slog-http with golang 1.22.2.

`2024/06/26 08:50:39 http: superfluous response.WriteHeader call from github.com/samber/slog-http.(*bodyWriter).WriteHeader (dump.go:53)`

Is this warning legit or is the stdlib confused?

Best,
Troy

**Comment by samber** [comment]
`WriteHeader` must be called before `Write` or not called at all.

This is not an error from this library, even if the warning seems to direct you here ;)
